title: "Mr.Mou @ ShiShi AP Center"
author: "Mr.Mou"
description: "Mr.Mou -- Apple Teacher with Swift Playgrounds Recognition"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "intro_to_cs.md", title: "CS Intro"}
  - {file: "APCSP.md", title: "AP CSP"}
  - {file: "APCSA.md", title: "AP CSA"}  
  - {title: "ESL", url: "https://apcentral.collegeboard.org/pdf/ap-computer-science-a-course-and-exam-description.pdf"}
  - {file: "post.md", title: "POSTS"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Apple, icon: apple, url: "https://appleteacher.apple.com/#/home/rp/T006361A?backTo=home%2Fprofile%2Fprogress"}
  - {title: Github, icon: github, url: "https://github.com/royhowtohack"}
  - {title: Wexin, icon: weixin, url: "https://weixin.qq.com/f/MLGtubJxdAmjxd7LyvwWjfA"}
  - {title: Mail, icon: envelope, url: "mailto:roy612723@gmail.com"}
  - {title: youtube, icon: youtube, url: "https://youtube.com/@roym4431"}
  
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 
